env:
  - GHCVER=7.8.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal-1.18 update
  - patch $HOME/.cabal/config < config.patch
  - cabal-1.18 update
  - ghc-pkg list
  - cabal-1.18 install progression-0.5.0.3
  - ghc-pkg list

matrix:
  allow_failures:
   - env: GHCVER=head
